import path from 'node:path'
import { defineConfig, mergeConfig } from 'vitest/config'
import { tanstackViteConfig } from '@tanstack/vite-config'
import packageJson from './package.json'
import type { Plugin } from 'vite'

/**
 * Vite plugin that rewrites the absolute worker URL generated by the
 * `?worker` import to use `import.meta.url`-relative resolution.
 *
 * Without this fix, the built output contains an absolute path like
 * `new Worker("/assets/opfs-worker-ABC123.js")` which only works if
 * the consumer serves the file at that exact path. Using
 * `new URL("../assets/...", import.meta.url)` instead makes it
 * relative to the module location, which consumer bundlers (Vite,
 * webpack 5) can detect and reprocess.
 */
function workerImportMetaUrlPlugin(): Plugin {
  return {
    name: `worker-import-meta-url`,
    enforce: `post`,
    generateBundle(_, bundle) {
      for (const chunk of Object.values(bundle)) {
        if (chunk.type !== `chunk`) continue

        const workerUrlMatch = chunk.code.match(/new Worker\(\s*"(\/[^"]+)"/)
        if (!workerUrlMatch?.[1]) continue

        const absolutePath = workerUrlMatch[1]
        const assetPath = absolutePath.slice(1)
        const chunkDir = path.dirname(chunk.fileName)
        const relativePath = path.relative(chunkDir, assetPath)

        chunk.code = chunk.code.replace(
          `"${absolutePath}"`,
          `new URL("${relativePath}", import.meta.url)`,
        )
      }
    },
  }
}

const config = defineConfig({
  plugins: [workerImportMetaUrlPlugin()],
  test: {
    name: packageJson.name,
    include: [`tests/**/*.test.ts`],
    environment: `node`,
    coverage: { enabled: true, provider: `istanbul`, include: [`src/**/*`] },
    typecheck: {
      enabled: true,
      include: [`tests/**/*.test.ts`, `tests/**/*.test-d.ts`],
    },
  },
})

export default mergeConfig(
  config,
  tanstackViteConfig({
    entry: `./src/index.ts`,
    srcDir: `./src`,
  }),
)
