import postgres from 'postgres'

// Test-only adapter. No change to Endpoints scheduling or application drivers.
export const strategies = {
  serial: { max: 1, max_pipeline: 0 },
  pipeline: { max: 1, max_pipeline: 100 },
  pool: { max: 3, max_pipeline: 0 },
}

export function connect(
  strategy = 'pipeline',
  port = 55479,
  { prepare = true } = {},
) {
  if (!Object.hasOwn(strategies, strategy)) throw Error('Unknown strategy')
  return postgres({
    host: '127.0.0.1',
    port,
    database: 'endpoints_pipeline',
    username: 'postgres',
    password: '',
    ssl: false,
    ...strategies[strategy],
    prepare,
    idle_timeout: 0,
    max_lifetime: 0,
    connect_timeout: 5,
    connection: {
      application_name: 'endpoints-pipeline-probe',
      timezone: 'UTC',
    },
    onnotice: () => {},
  })
}

export async function execute(sql, query) {
  // SQL text is generated by the server-owned fixture. All values stay bound.
  // Force extended protocol even for zero parameters. Warm prepared queries
  // can pipeline; a cold parameterized query first needs type description.
  const rows = await sql.unsafe(query.text, query.params ?? [], {
    prepare: true,
    simple: false,
  })
  return Array.from(rows)
}

export function readFunctions(sql, queries) {
  return Object.fromEntries(
    queries.map((query) => [query.id, () => execute(sql, query)]),
  )
}

export function decode(response) {
  if (response.kind === 'confirmed') return response.snapshots
  if (response.kind === 'confirmed-shared')
    return response.snapshots.map(({ id, indexes }) => ({
      id,
      rows: indexes.map((index) => response.pool[index]),
    }))
  throw Error(`No confirmed snapshots: ${response.kind}`)
}
