/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsrDbRouteImport } from './routes/ssr-db'
import { Route as IndexRouteImport } from './routes/index'

const SsrDbRoute = SsrDbRouteImport.update({
  id: '/ssr-db',
  path: '/ssr-db',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ssr-db': typeof SsrDbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ssr-db': typeof SsrDbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ssr-db': typeof SsrDbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ssr-db'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ssr-db'
  id: '__root__' | '/' | '/ssr-db'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SsrDbRoute: typeof SsrDbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ssr-db': {
      id: '/ssr-db'
      path: '/ssr-db'
      fullPath: '/ssr-db'
      preLoaderRoute: typeof SsrDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SsrDbRoute: SsrDbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
