/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProbeControlRouteImport } from './routes/probe-control'
import { Route as IndexRouteImport } from './routes/index'

const ProbeControlRoute = ProbeControlRouteImport.update({
  id: '/probe-control',
  path: '/probe-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/probe-control': typeof ProbeControlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/probe-control': typeof ProbeControlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/probe-control': typeof ProbeControlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/probe-control'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/probe-control'
  id: '__root__' | '/' | '/probe-control'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProbeControlRoute: typeof ProbeControlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/probe-control': {
      id: '/probe-control'
      path: '/probe-control'
      fullPath: '/probe-control'
      preLoaderRoute: typeof ProbeControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProbeControlRoute: ProbeControlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
