/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiIssuesRouteImport } from './routes/api/issues'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiIssuesUpdateRouteImport } from './routes/api/issues/update'
import { Route as ApiIssuesDeleteRouteImport } from './routes/api/issues/delete'
import { Route as ApiIssuesCreateRouteImport } from './routes/api/issues/create'
import { Route as ApiIssuesCountRouteImport } from './routes/api/issues/count'
import { Route as ApiCommentsDeleteRouteImport } from './routes/api/comments/delete'
import { Route as ApiCommentsCreateRouteImport } from './routes/api/comments/create'
import { Route as ApiCommentsByIssueRouteImport } from './routes/api/comments/by-issue'
import { Route as AuthenticatedIssueIssueIdRouteImport } from './routes/_authenticated/issue/$issueId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiIssuesRoute = ApiIssuesRouteImport.update({
  id: '/api/issues',
  path: '/api/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssuesUpdateRoute = ApiIssuesUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiIssuesDeleteRoute = ApiIssuesDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiIssuesCreateRoute = ApiIssuesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiIssuesCountRoute = ApiIssuesCountRouteImport.update({
  id: '/count',
  path: '/count',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiCommentsDeleteRoute = ApiCommentsDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentsCreateRoute = ApiCommentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentsByIssueRoute = ApiCommentsByIssueRouteImport.update({
  id: '/by-issue',
  path: '/by-issue',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const AuthenticatedIssueIssueIdRoute =
  AuthenticatedIssueIssueIdRouteImport.update({
    id: '/issue/$issueId',
    path: '/issue/$issueId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/issue/$issueId': typeof AuthenticatedIssueIssueIdRoute
  '/api/comments/by-issue': typeof ApiCommentsByIssueRoute
  '/api/comments/create': typeof ApiCommentsCreateRoute
  '/api/comments/delete': typeof ApiCommentsDeleteRoute
  '/api/issues/count': typeof ApiIssuesCountRoute
  '/api/issues/create': typeof ApiIssuesCreateRoute
  '/api/issues/delete': typeof ApiIssuesDeleteRoute
  '/api/issues/update': typeof ApiIssuesUpdateRoute
}
export interface FileRoutesByTo {
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/issue/$issueId': typeof AuthenticatedIssueIssueIdRoute
  '/api/comments/by-issue': typeof ApiCommentsByIssueRoute
  '/api/comments/create': typeof ApiCommentsCreateRoute
  '/api/comments/delete': typeof ApiCommentsDeleteRoute
  '/api/issues/count': typeof ApiIssuesCountRoute
  '/api/issues/create': typeof ApiIssuesCreateRoute
  '/api/issues/delete': typeof ApiIssuesDeleteRoute
  '/api/issues/update': typeof ApiIssuesUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/issue/$issueId': typeof AuthenticatedIssueIssueIdRoute
  '/api/comments/by-issue': typeof ApiCommentsByIssueRoute
  '/api/comments/create': typeof ApiCommentsCreateRoute
  '/api/comments/delete': typeof ApiCommentsDeleteRoute
  '/api/issues/count': typeof ApiIssuesCountRoute
  '/api/issues/create': typeof ApiIssuesCreateRoute
  '/api/issues/delete': typeof ApiIssuesDeleteRoute
  '/api/issues/update': typeof ApiIssuesUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/comments'
    | '/api/issues'
    | '/'
    | '/issue/$issueId'
    | '/api/comments/by-issue'
    | '/api/comments/create'
    | '/api/comments/delete'
    | '/api/issues/count'
    | '/api/issues/create'
    | '/api/issues/delete'
    | '/api/issues/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/comments'
    | '/api/issues'
    | '/'
    | '/issue/$issueId'
    | '/api/comments/by-issue'
    | '/api/comments/create'
    | '/api/comments/delete'
    | '/api/issues/count'
    | '/api/issues/create'
    | '/api/issues/delete'
    | '/api/issues/update'
  id:
    | '__root__'
    | '/_authenticated'
    | '/api/comments'
    | '/api/issues'
    | '/_authenticated/'
    | '/_authenticated/issue/$issueId'
    | '/api/comments/by-issue'
    | '/api/comments/create'
    | '/api/comments/delete'
    | '/api/issues/count'
    | '/api/issues/create'
    | '/api/issues/delete'
    | '/api/issues/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiCommentsRoute: typeof ApiCommentsRouteWithChildren
  ApiIssuesRoute: typeof ApiIssuesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/issues': {
      id: '/api/issues'
      path: '/api/issues'
      fullPath: '/api/issues'
      preLoaderRoute: typeof ApiIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issues/update': {
      id: '/api/issues/update'
      path: '/update'
      fullPath: '/api/issues/update'
      preLoaderRoute: typeof ApiIssuesUpdateRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/issues/delete': {
      id: '/api/issues/delete'
      path: '/delete'
      fullPath: '/api/issues/delete'
      preLoaderRoute: typeof ApiIssuesDeleteRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/issues/create': {
      id: '/api/issues/create'
      path: '/create'
      fullPath: '/api/issues/create'
      preLoaderRoute: typeof ApiIssuesCreateRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/issues/count': {
      id: '/api/issues/count'
      path: '/count'
      fullPath: '/api/issues/count'
      preLoaderRoute: typeof ApiIssuesCountRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/comments/delete': {
      id: '/api/comments/delete'
      path: '/delete'
      fullPath: '/api/comments/delete'
      preLoaderRoute: typeof ApiCommentsDeleteRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comments/create': {
      id: '/api/comments/create'
      path: '/create'
      fullPath: '/api/comments/create'
      preLoaderRoute: typeof ApiCommentsCreateRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comments/by-issue': {
      id: '/api/comments/by-issue'
      path: '/by-issue'
      fullPath: '/api/comments/by-issue'
      preLoaderRoute: typeof ApiCommentsByIssueRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/_authenticated/issue/$issueId': {
      id: '/_authenticated/issue/$issueId'
      path: '/issue/$issueId'
      fullPath: '/issue/$issueId'
      preLoaderRoute: typeof AuthenticatedIssueIssueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIssueIssueIdRoute: typeof AuthenticatedIssueIssueIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIssueIssueIdRoute: AuthenticatedIssueIssueIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiCommentsRouteChildren {
  ApiCommentsByIssueRoute: typeof ApiCommentsByIssueRoute
  ApiCommentsCreateRoute: typeof ApiCommentsCreateRoute
  ApiCommentsDeleteRoute: typeof ApiCommentsDeleteRoute
}

const ApiCommentsRouteChildren: ApiCommentsRouteChildren = {
  ApiCommentsByIssueRoute: ApiCommentsByIssueRoute,
  ApiCommentsCreateRoute: ApiCommentsCreateRoute,
  ApiCommentsDeleteRoute: ApiCommentsDeleteRoute,
}

const ApiCommentsRouteWithChildren = ApiCommentsRoute._addFileChildren(
  ApiCommentsRouteChildren,
)

interface ApiIssuesRouteChildren {
  ApiIssuesCountRoute: typeof ApiIssuesCountRoute
  ApiIssuesCreateRoute: typeof ApiIssuesCreateRoute
  ApiIssuesDeleteRoute: typeof ApiIssuesDeleteRoute
  ApiIssuesUpdateRoute: typeof ApiIssuesUpdateRoute
}

const ApiIssuesRouteChildren: ApiIssuesRouteChildren = {
  ApiIssuesCountRoute: ApiIssuesCountRoute,
  ApiIssuesCreateRoute: ApiIssuesCreateRoute,
  ApiIssuesDeleteRoute: ApiIssuesDeleteRoute,
  ApiIssuesUpdateRoute: ApiIssuesUpdateRoute,
}

const ApiIssuesRouteWithChildren = ApiIssuesRoute._addFileChildren(
  ApiIssuesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiCommentsRoute: ApiCommentsRouteWithChildren,
  ApiIssuesRoute: ApiIssuesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
