name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@scape-app'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Set version suffix
        run: |
          SUFFIX="fork.$(date +%Y%m%d%H%M%S)"
          echo "VERSION_SUFFIX=$SUFFIX" >> $GITHUB_ENV

      - name: Update package versions
        run: |
          cd packages/db
          npm version prerelease --preid=${{ env.VERSION_SUFFIX }} --no-git-tag-version
          cd ../react-db
          npm version prerelease --preid=${{ env.VERSION_SUFFIX }} --no-git-tag-version
          cd ../query-db-collection
          npm version prerelease --preid=${{ env.VERSION_SUFFIX }} --no-git-tag-version
          cd ../electric-db-collection
          npm version prerelease --preid=${{ env.VERSION_SUFFIX }} --no-git-tag-version

      - name: Publish packages
        run: |
          cd packages/db && npm publish
          cd ../react-db && npm publish
          cd ../query-db-collection && npm publish
          cd ../electric-db-collection && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
